## Практическое задание

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__РЕШЕНИЕ__

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}\Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}\Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & 1 & 0 & -6.5\\ 
0 & 0 & 1 & -1.5
\end{matrix}\right|
\begin{matrix}
-2\\ 
0\\
-2\\
\end{matrix}
\end{pmatrix}\Leftrightarrow\begin{cases}
x_{1}=-2-3x_4 \\
x_{2}=6.5x_4 \\
x_{3}=1.5x_4-2
\end{cases}$$

СЛАУ имеет бесконечное кол-во решение указанного вида

__Теорема__ 

Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$$rank A=rank \tilde A.$$

Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}\leftrightarrow\begin{cases}
x_{1}=1, \\
x_{3}=3, \\
x_{2}=2;
\end{cases}$



In [3]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
Ar = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(Ar))

Ранг матрицы коэфициентов: 3
Ранг расширенной матрицы: 3


а) Система определена, имеет единственное решение

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}\leftrightarrow \begin{cases}
0=5, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
0=11;
\end{cases}$



In [4]:
A = np.array([[2,-4,-6],[1,-2,3],[3,-6,9]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
Ar = np.array([[2,-4,-6,1],[1,-2,3,-2],[3,-6,9,5]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(Ar))

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 3


б) Система несовместна

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases} \leftrightarrow\begin{cases}
5x_{1} = 21x_3 - 8, \\
5x_{2} = 14 - 23x_3 
\end{cases}$



In [6]:
A = np.array([[1,2,5],[3,1,-8]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
Ar = np.array([[1,2,5,4],[3,1,-8,-2]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(Ar))

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 2


в) Система имеет бесконечное число решений, так как ранг матриц  < числа неизвестных

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$


In [7]:
A = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])
A_ = np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])

print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))
print("Согласно Теореме Кронекера — Капелли система совместима и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных")

Ранг матрицы коэфициентов: 4
Ранг расширенной матрицы: 4
Согласно Теореме Кронекера — Капелли система совместима и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

В случае если равенство

$c = 2b - a$

не выполняется, система является не совместной

__5.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

### Метод Крамера

Для системы с $n$ уравнениями и $n$ неизвестными, если система уравнений невырождена (то есть $detA\neq 0$), то система определена, то есть имеет единственное решение, и это решение может быть найдено по формулам Крамера:

$$x_{i}=\frac{detA_{i}}{detA},$$

где $A_{i}$ — это матрица, получаемая заменой $i$-го столбца на вектор-столбец свободных членов $b$.

In [8]:
A = np.array([[1,-2],[3,-4]])
A1 = np.array([[1,-2],[7,-4]])
A2 = np.array([[1,1],[3,7]])
print(f'х1 = {np.linalg.det(A1)/np.linalg.det(A):.0f}')
print(f'х2 = {np.linalg.det(A2)/np.linalg.det(A):.0f}')

х1 = 5
х2 = 2


 __6.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

  $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [16]:
# LU decomposition
from scipy.linalg import lu
# define a square matrix
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
print(A)
# LU decomposition
P, L, U = lu(A)
print(P)
print('Матрица L ')
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Матрица L 
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
[[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]
[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]


__7.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [26]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = lu(A)
print(L)

[[ 1.    0.    0.  ]
 [ 0.82  1.    0.  ]
 [ 0.18 -0.12  1.  ]]


In [24]:
print(U)

[[11.    7.    5.  ]
 [ 0.    2.27 -0.09]
 [ 0.    0.    2.08]]


Вычисляем значения yi

y1 = 1/2 = 0.5

y2 = (-6 - 11 • 0.5 )/1.5 = -7.67

y3 = (-5 - 9 • 0.5 + 3.5 • (-7.67) )/17.33 = 1


Вычисляем значения xi

x3 = y3 = 1

x2 = -7.67 - (-7.67 • 1 ) = 0

x1 = 0.5 - (0.5 • 0 + 1.5 • 1 ) = -1


__8.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [22]:
from numpy.linalg import cholesky
# define a 3x3 matrix
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
# Cholesky decomposition
L = cholesky(A)
print(L)

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$


y3 = 59;
y2 = -444/7
y1 = 200/7

In [21]:
LT = L.T
print(LT)

[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]


И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}+(-5)x_{2}+5x_{3}=\frac{200}{7}, \\
5x_{2}+2x_{3}=\frac{-444}{7}, \\
3x_{3}=59.
\end{cases}$$


9. 1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [18]:
np.set_printoptions(precision=2, suppress=True)
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
U, s, W = np.linalg.svd(A)
# Транспонируем матрицу W
V = W.T
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]
