# Матрицы и матричные операции.

In [2]:
import numpy as np

## Практическое задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)
   
   
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - неопределена; $BA$ - $2\times 3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $3\times 3$; $BA$ - $8\times 8$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

# 1. 

### a) 𝐴  — матрица 4×2, 𝐵 — матрица 4×2
      


In [10]:
A = np.array([[1, 0], [2, 1], [10, 5], [10, 5]])
B = np.array([[2, 0], [0, 0],  [10, 5], [10, 5]])
print(f'Матрица AB\n{np.dot(A, B)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [5]:
print(f'Матрица BA\n{np.dot(B, A)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

### б)𝐴  — матрица 2×5, 𝐵 — матрица 5×3;

In [12]:
A = np.array([[1, 0, 4, 2, 3], [2, 1, 2, 1, 2]])
B = np.array([[2, 0, 4], [0, 0, 2],  [10, 5, 3], [10, 5, 2], [10, 25, 2]])
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица AB
[[ 92 105  26]
 [ 54  65  22]]


In [7]:
print(f'Матрица BA\n{np.dot(B, A)}')

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

### В)   𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 

In [15]:
A = np.array([[2, 0, 4], [2, 0, 4],[2, 0, 4],[2, 0, 4],[2, 0, 4],[2, 0, 4],[2, 0, 4],[2, 0, 4],])
B = np.array([[2, 0, 4, 4, 5,6,7,8], [2, 0, 4, 4, 5,6,7,8],  [2, 0, 4, 4, 5,6,7,8]])
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица AB
[[12  0 24 24 30 36 42 48]
 [12  0 24 24 30 36 42 48]
 [12  0 24 24 30 36 42 48]
 [12  0 24 24 30 36 42 48]
 [12  0 24 24 30 36 42 48]
 [12  0 24 24 30 36 42 48]
 [12  0 24 24 30 36 42 48]
 [12  0 24 24 30 36 42 48]]


In [16]:
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица BA
[[ 72   0 144]
 [ 72   0 144]
 [ 72   0 144]]


### г) 𝐴  — квадратная матрица 4×4, 𝐵 — квадратная матрица 4×4

In [18]:
A = np.array([[1, 0, 4, 2], [2, 1, 2, 1], [2, 1, 2, 1], [2, 1, 2, 1]])
B = np.array([[2, 1, 2, 1],[2, 1, 2, 1],[2, 1, 2, 1],[2, 1, 2, 1]])
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица AB
[[14  7 14  7]
 [12  6 12  6]
 [12  6 12  6]
 [12  6 12  6]]


In [19]:
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица BA
[[10  4 16  8]
 [10  4 16  8]
 [10  4 16  8]
 [10  4 16  8]]


### Выводы: 
        а) недопустимые операции, матрицы неопределены
        б) AB - (2;3), BA неопределена
        в) АВ - (8;8), ВА - (3;3)
        г) AB - (4;4), BA - (4;4)

### 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ 

In [20]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [23]:
print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


#### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [27]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = \n{A*3+(-2)*B+4*C}") 


Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [32]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.T
print(f'Матрица AAt\n{np.dot(A, At)}\n')

Матрица AAt
[[17 18 11]
 [18 29  4]
 [11  4 13]]



In [33]:
print(f'Матрица AtA\n{np.dot(At, A)}\n')

Матрица AtA
[[45  0]
 [ 0 14]]




__5.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [43]:
x = 1;
a = np.array([[np.sin(x), -(np.cos(x))], [np.cos(x), np.sin(x)]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
1


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [44]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [45]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
-0


определитель такой матрицы равен 0 т.к если из второй и третьей строки вычесть первую то вторая и третья строки будет линейно зависимыми

__6.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

###### Матрица называется _сингулярной_, или _вырожденной_, если ее определитель равен нулю.

In [46]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
0


__7.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [47]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2
