# Numpy

In [4]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [ ]:
arr = np.zeros(100)
print(arr)

#### 2.Создать вектор размера 100, заполненный единицами

In [ ]:
arr = np.ones(100)
print(arr)

#### 3.Создать вектор размера 100, заполненный числом 3

In [2]:
arr = [3]*100
print(arr)

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [ ]:
help (np.add)

#### 5. Поменять 2 строки в матрице

In [11]:
matrix = np.arange(4).reshape(2,2)
matrix[[0,1]] = matrix[[1,0]]
print(matrix)

[[2 3]
 [0 1]]


#### 6. Создать вектор со значениями от 10 до 100

In [12]:
arr = np.linspace(10,100,12)[1:-1]
print(arr)

[18.18181818 26.36363636 34.54545455 42.72727273 50.90909091 59.09090909
 67.27272727 75.45454545 83.63636364 91.81818182]


#### 7. Развернуть вектор (первый становится последним)

In [14]:
arr = np.arange(10)
arr = arr[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [15]:
matrix = np.arange(16).reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


/9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [18]:
arr = np.array([1,2,3,4,5])
z = 3
arr0 = np.zeros(len(arr) + (len(arr)-1)*(z))
arr0[::z+1] = arr
print(arr0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 10. Создать 3x3 единичную матрицу

In [4]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [5]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.38692857 0.66986504 0.28576767]
  [0.28019839 0.53903142 0.43519383]
  [0.48031459 0.31649065 0.16104274]]

 [[0.81766517 0.88246763 0.53451881]
  [0.51455303 0.24749141 0.43068348]
  [0.08848848 0.80197141 0.05738466]]

 [[0.98693285 0.77867741 0.01206755]
  [0.01687361 0.46417828 0.76810784]
  [0.45846841 0.75756589 0.71040663]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [6]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.018885559280569564 0.9855320700093096


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [19]:
arr = np.random.random(30)
m = arr.mean()
print(m)

0.535673226508769


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [21]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

16. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [27]:
arr = np.diag(np.arange(1, 5), k=1)
print(arr)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [28]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [29]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(arr)

#### 20. Перемножить матрицы 5x3 и 3x2

In [ ]:
matrix = np.dot(np.ones((5,3)), np.ones((3,2)))
print(matrix)

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [30]:
arr = np.arange(20)
arr[(3 < arr) & (arr <= 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [31]:
arr = np.ones((5,5))
arr += np.arange(5)
print(arr)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


#### 24. Есть генератор, сделать с его помощью массив

In [37]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(),dtype ="int",count=-1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [38]:
arr = np.linspace(0,1,12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [40]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.03176162 0.04135146 0.29396128 0.3086438  0.46185514 0.70331111
 0.86946146 0.937695   0.96714223 0.98041187]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [45]:
A = [1,2,3]
B = [0,2,10]
equal = np.allclose(A,B)
print(equal)

False


#### 28. Сделать массив неизменяемым

In [46]:
arr = np.zeros(10)
arr.flags.writeable = False


#### 29. Найти n наибольших значений в массиве

In [47]:
arr = np.arange(100)
np.random.shuffle(arr)
n = 5
print (arr[np.argpartition(-arr,n)[:n]])

[99 98 97 96 95]


#### 30. Заменить максимальный элемент на ноль

In [49]:
arr = np.arange(10)
arr[arr.argmax()] = 0
print(arr)

[0 1 2 3 4 5 6 7 8 0]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [50]:
arr = np.zeros((10,10), [('x',int),('y',int)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(arr)

[[(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (1, 1)]]


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [51]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [52]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [60]:
np.set_printoptions(threshold=1)
arr = np.ones((25,25))
print(arr)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [61]:
arr = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr-v)).argmin()
print(arr[index])


51


#### 36. Преобразовать массив из float в int

In [64]:
arr = np.arange(20, dtype=np.int32)
print(arr)
arr = arr.astype(np.float32, copy=False)
print(arr)

[ 0  1  2 ... 17 18 19]
[ 0.  1.  2. ... 17. 18. 19.]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [66]:
arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [68]:
n = 10
p = 2
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False), 1)
print(arr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 39. Отнять среднее из каждой строки в матрице

In [73]:
X = np.random.rand(1, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(X)
print(Y)

[[0.61764067 0.54755056 0.65713913 ... 0.86002448 0.3631977  0.19856547]]
[[ 0.07225991  0.0021698   0.11175837 ...  0.31464372 -0.18218306
  -0.34681529]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [75]:
matrix = np.random.randint(0,10,(3,3))
n = 1 
print(matrix)
print(matrix[matrix[:,n].argsort()])

[[3 8 7]
 [4 1 7]
 [7 9 7]]
[[4 1 7]
 [3 8 7]
 [7 9 7]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [76]:
arr = np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [78]:
arr = np.zeros(10)
arr1 = np.random.randint(0,len(arr),20)
arr += np.bincount(arr1, minlength=len(arr))
print(arr)

[2. 2. 1. ... 2. 3. 2.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [79]:
w,h = 16,16
arr = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
arrF = arr[...,0] * 256 * 256 + arr[...,1] * 256 + arr[...,2]
n = len(np.unique(arrF))
print(np.unique(arr))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [80]:
arr4 = np.random.randint(0,10, (3,4,3,4))
sum = arr4.reshape(arr4.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 54 49 50]
 [33 62 53 56]
 [53 73 57 45]]
